### ISSUE TITLE
Link in documentation still refers to the hg site

### ISSUE THREAD

**Issue by zerothi** [haraldkl/aotus#10]
I guess you are aware of this, so perhaps just a place-holder.

**Comment by haraldkl** [comment]
Thanks a lot. I am currently moving the various other repositories that I need to take care of, and will get back at the documentation, once I've got our complete setup running again. But it's useful to have issues as reminders. I am grateful for any pointing out of inconsistencies.

**Comment by haraldkl** [comment]
Should be resolved now, and https://geb.inf.tu-dresden.de/doxy/aotus/index.html should now point to github rather than OSDN.
